#!/bin/bash
# Update the package list
sudo apt-get update -y

# Install Java (OpenJDK 11)
sudo apt-get install openjdk-11-jdk -y

sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update -y
sudo apt-get install jenkins -y

# Start Jenkins service and enable it to start on boot
sudo systemctl start jenkins
sudo systemctl enable jenkins

echo "Jenkins Installed"
